#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Silent Rave — Phase 3b test suite (manual payment).
#
#   bun run test:phase3b
#
# ONE command, repeatable, runs from the fixture rebuild alone:
#   1. `bun run db:fixture` — wipes + rebuilds the embedded Postgres fixture
#      (fresh .env with fresh secrets, migrate deploy, OWNER + event +
#      active payment account seeds)
#   2. restarts the dev server on :3000 with the fresh env, STRICT Origin
#      checks (ALLOW_DEV_ORIGIN deliberately UNSET — the suite drives admin
#      routes with the proper admin.localhost surface origin, proving the
#      default-strict behaviour end-to-end)
#   3. runs the bun test files in tests/phase3b/ against the live server
#   4. restores the normal dev server on exit (trap) WITH ALLOW_DEV_ORIGIN=1
#      so sandbox preview-gateway browsing/login keeps working
#
# Nothing external is mocked — payment is manual (no Paystack). The image
# library (sharp) is REAL, not mocked; all proof images are generated by
# sharp in-test.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail
cd "$(dirname "$0")/../.."

DB_URL="postgresql://postgres@127.0.0.1:54329/silentrave"
TEST_DB_URL="${DB_URL}?connection_limit=8"

echo "▸ 1/4 rebuilding the local fixture from scratch (bun run db:fixture)"
bun run db:fixture

echo "▸ 2/4 (re)starting the dev server on :3000"
DEV_PIDS="$(ss -ltnp 2>/dev/null | grep ':3000 ' | grep -o 'pid=[0-9]*' | cut -d= -f2 | sort -u || true)"
if [ -n "${DEV_PIDS}" ]; then
  echo "  stopping previous dev server (pids: ${DEV_PIDS})"
  kill ${DEV_PIDS} 2>/dev/null || true
  sleep 2
fi
(setsid env DATABASE_URL="${TEST_DB_URL}" bun run dev >/dev/null 2>&1 </dev/null &)

echo "▸ waiting for dev server readiness"
READY=0
for _ in $(seq 1 60); do
  if curl -s -o /dev/null http://127.0.0.1:3000/ 2>/dev/null; then
    READY=1
    break
  fi
  sleep 1
done
if [ "${READY}" != "1" ]; then
  echo "✖ dev server did not become ready — check dev.log" >&2
  exit 1
fi

# Always restore a normal dev server afterwards — with the dev Origin
# relaxation opted in (preview-gateway browsing needs same-origin auth on an
# external hostname; STRICT default would block it).
cleanup() {
  echo ""
  echo "▸ restoring the normal dev server"
  DEV_PIDS="$(ss -ltnp 2>/dev/null | grep ':3000 ' | grep -o 'pid=[0-9]*' | cut -d= -f2 | sort -u || true)"
  if [ -n "${DEV_PIDS}" ]; then
    kill ${DEV_PIDS} 2>/dev/null || true
    sleep 2
  fi
  (setsid env DATABASE_URL="${TEST_DB_URL}" ALLOW_DEV_ORIGIN=1 bun run dev >/dev/null 2>&1 </dev/null &)
}
trap cleanup EXIT

echo "▸ 3/4 running the Phase 3b test suite"
env TEST_DATABASE_URL="${TEST_DB_URL}" bun test tests/phase3b/

echo "▸ 4/4 done"
